import { api } from "#lib/api-client"
import type {
  AnalyticsOverview,
  AssignmentShareResponse,
  CourseComparisonRow,
  PaginatedResult,
  PublicAttemptResultResponse,
  PublicAttemptStartResponse,
  Question,
  StudentPerformance,
  Test,
  TestAssignment,
  TestAttempt,
  TestStats,
} from "#lib/types"

export const testsApi = {
  listQuestions: (query = "") => api.get<PaginatedResult<Question>>(`/tests/questions${query}`),
  getQuestion: (id: string) => api.get<Question>(`/tests/questions/${id}`),
  createQuestion: (body: unknown) => api.post<Question>("/tests/questions", body),
  updateQuestion: (id: string, body: unknown) => api.patch<Question>(`/tests/questions/${id}`, body),
  archiveQuestion: (id: string) => api.post<Question>(`/tests/questions/${id}/archive`),
  deleteQuestion: (id: string) => api.delete<void>(`/tests/questions/${id}`),
  listTests: (query = "") => api.get<PaginatedResult<Test>>(`/tests${query}`),
  getTest: (id: string) => api.get<Test>(`/tests/${id}`),
  createTest: (body: unknown) => api.post<Test>("/tests", body),
  updateTest: (id: string, body: unknown) => api.patch<Test>(`/tests/${id}`, body),
  publishTest: (id: string) => api.post<Test>(`/tests/${id}/publish`),
  archiveTest: (id: string) => api.post<Test>(`/tests/${id}/archive`),
  listAssignments: (query = "") => api.get<TestAssignment[]>(`/tests/assignments${query}`),
  assignTest: (testId: string, body: unknown) => api.post<TestAssignment[]>(`/tests/${testId}/assignments`, body),
  revokeAssignment: (id: string) => api.patch<TestAssignment>(`/tests/assignments/${id}/revoke`),
  allowRetake: (id: string) => api.patch<TestAssignment>(`/tests/assignments/${id}/retake`),
  listAttempts: (query = "") => api.get<PaginatedResult<TestAttempt>>(`/tests/attempts${query}`),
  getAttempt: (id: string) => api.get<TestAttempt>(`/tests/attempts/${id}`),
  analyticsOverview: () => api.get<AnalyticsOverview>("/tests/analytics/overview"),
  testAnalytics: (testId: string) => api.get<TestStats>(`/tests/analytics/tests/${testId}`),
  courseComparison: () => api.get<CourseComparisonRow[]>("/tests/analytics/courses"),
  leaderboard: () => api.get<StudentPerformance[]>("/tests/analytics/leaderboard"),
  publicAssignment: (shareToken: string) => api.get<AssignmentShareResponse>(`/tests/share/${shareToken}`),
  startPublicAttempt: (shareToken: string) => api.post<PublicAttemptStartResponse>(`/tests/share/${shareToken}/start`),
  savePublicProgress: (shareToken: string, body: unknown) => api.patch(`/tests/share/${shareToken}/progress`, body),
  submitPublicAttempt: (shareToken: string, body: unknown) => api.post(`/tests/share/${shareToken}/submit`, body),
  publicResult: (shareToken: string) => api.get<PublicAttemptResultResponse>(`/tests/share/${shareToken}/result`),
}